### ISSUE TITLE
TypeError: users.insert is not a function

### ISSUE THREAD

**Issue by alexanderbuhler** [eastolfi/MongoPortable#17]
Hey, I was just trying to find out why the example code doesn't work but after struggling for some hours now I'm just going to post it here.

While getting the collection `db.collection("users")` there's a Promise coming back but its not implementing an insert function as a Collection object would. I'm going to admin that I'm a bit rusty about node but it seems that Promises just doesn't get resolved...

I'm using this example code:

```
// Declaring the modules dependencies
var MongoPortable = require("mongo-portable").MongoPortable,
	FileSystemStore = require("file-system-store").FileSystemStore;

// Instantiates a new ddbb object by passing a ddbb name
var db = new MongoPortable("TEST");

// Tells MongoPortable to use this store to persist the data
db.addStore(new FileSystemStore({
	// The path where the database will be stored
	ddbb_path: "dbtest",
	// Whether the persistance will be asynchronous or not
	sync: true
}));

// Creates a new collection named "users" 
//      (if it's already created, it will just return it instead)
var users = db.collection("users");

// Inserts a new document into the collection
var document = users.insert({ name: "John", lastName: "Abruzzi" });
console.log(document);  // -> { name: "John", lastName: "Abruzzi" }

// Creates a cursor with the query information, ready to be fetched
var cursor = users.find({ name: "John" });

// Iterates over the cursor, obtaining each document that matchs the query
cursor.forEach(function (doc) {
	console.log(doc);  // -> { name: "John", lastName: "Abruzzi" }
});
```

This is the output:

```
$ node example.js
window not found -> not a browser environment
INFO: Emitting store event "createCollection"
/Users/alexander/GIT/reno-f3base-server/example.js:21
var document = users.insert({ name: "John", lastName: "Abruzzi" });
                     ^

TypeError: users.insert is not a function
    at Object.<anonymous> (/Users/alexander/GIT/reno-f3base-server/example.js:21:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Tried with node versions 8.11, 6.6 and 4.4 on OSX

**Comment by alexanderbuhler** [comment]
Nevermind, just figured out it's simply old documentation on github – the most recent one (>v2.0) takes promises into account by using `then`.
